### ISSUE TITLE
socks5

### ISSUE THREAD

**Issue by ahmedaman0000** [Smartproxy/Selenium-proxy-authentication#7]
hello,
How can I use socks 5?

**Comment by 4ofour** [comment]
I found it to be possible using Selenium-wire, like so:
`from seleniumwire import webdriver

options = {
    'proxy': {
        'http': 'socks5://user:pass@gate.smartproxy.com:10001',
        'https': 'socks5://user:pass@gate.smartproxy.com:10001',
        'no_proxy': 'localhost,gate.smartproxy.com:10001'
    }
}

driver = webdriver.Chrome(seleniumwire_options=options)`
